### ISSUE TITLE
Different result when running mk_prepare_ligand.py

### ISSUE THREAD

**Issue by jiayuanz3** [ccsb-scripps/AutoDock-Vina#119]
Hi there,

I was trying to run mk_prepare_ligand.py to prepare ligand (sdf format to pdbqt format). I tried the exact same command (mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt) for original 1iep_ligand.sdf provided in the Github page. However, I got different output than expected. Could you help me to figure it out?
p.s. left of the image is downloaded from Github, right hand side is my generated result.
Thanks in advance!
<img width="1134" alt="difference image" src="https://user-images.githubusercontent.com/69614741/179364698-632164a9-1dd7-4f6a-9a50-e02d44f0e9d9.png">

**Comment by diogomart** [comment]
The current meeko version expects the input molecule to have explicit hydrogens and 3D coordinates, but earlier versions added hydrogens. Since the ligand SDF in the tutorial data folder is missing hydrogens, the prepared PDBQT misses all the "HD" atoms. We will need to add a check to bail out on molecules with implicit hydrogens, and update the tutorial.

The "REMARK SMILES" at the top of the PDBQT are for making an RDKit molecule with docked coordinates. AutoDock-GPU and Vina print these remarks to the output file, and meeko uses those lines to build the RDKit molecule from SMILES and assign the coordinates, using the Python API ([example here](https://github.com/forlilab/Meeko#2-rdkit-molecule-from-docking-results)) or the script `mk_copy_coords.py`.

**Comment by diogomart** [comment]
Added check for implicit hydrogens: https://github.com/forlilab/Meeko/commit/05bdb0a1a1bf71ec82f59b9b1c25eaf7ad49e01b

**Comment by diogomart** [comment]
Check for 3D coords in input mol to be added eventually: https://github.com/forlilab/Meeko/issues/25
