### ISSUE TITLE
zinc_pseudo.py generates 0 TZ atoms

### ISSUE THREAD

**Issue by rczerminski-valo** [ccsb-scripps/AutoDock-Vina#149]
I have a structure with Zn atoms, however when I run 

`pythonsh <script_directory>/zinc_pseudo.py -r <protein>.pdbqt -o <protein>_tz.pdbqt`

I am getting: `Wrote 0 TZ atoms on [...]`

How to debug this issue?

**Comment by diogomart** [comment]
TZ atoms are only for zinc ions that can bind ligands in a tetrahedral geometry. If you have such a Zinc and believe a TZ should have been added, feel free to post the structure here (the zinc and the residues that coordinate it are sufficient).

**Comment by rczerminski-valo** [comment]
What would you recommend for structures containing zinc ion(s) interacting with ligands, but not in tetrahedral geometry? Standard vina (`--scoring vina`) or AutoDock4Zn (`--scoring ad4`)?

**Comment by diogomart** [comment]
That's a good question. I don't know. The AD4Zn potentials define potentials between Oxygen and Zn, and between Sulfur and Zn, which is more specific than Vina because Vina uses the H-bond potential for metal interactions, and H-bonds are all weighted equally. However, AD4Zn misses an interaction between Nitrogen and Zn (it has only a Nitrogen-TZ interaction), so for ligands that coordinate Zn with N atoms, and the geometry is not tetrahedral, it's possible that Vina gives you better results. However, we don't know for sure, because the dataset didn't have sufficient complexes with non-tetrahedral Nitrogen coordination.
