### ISSUE TITLE
internal error occurred in ../../../src/lib/model.cpp(682)

### ISSUE THREAD

**Issue by hrp1000** [ccsb-scripps/AutoDock-Vina#156]
error message - 

AutoDock Vina v1.2.3
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli  #
# AutoDock Vina 1.2.0: New Docking Methods, Expanded Force      #
# Field, and Python Bindings, J. Chem. Inf. Model. (2021)       #
# DOI 10.1021/acs.jcim.1c00203                                  #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, J. Comp. Chem. (2010)                         #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see https://github.com/ccsb-scripps/AutoDock-Vina for  #
# more information.                                             #
#################################################################

Output will be FAD_ideal_out.pdbqt
Scoring function : vina
Rigid receptor: 3qvp_A.pdbqt
Ligand: FAD_ideal.pdbqt
Grid center: X -296.579 Y -1485.05 Z 1274.2
Grid size  : X 10.283 Y 5.075 Z 24.783
Grid space : 0.375
Exhaustiveness: 8
CPU: 0
Verbosity: 1

Computing Vina grid ... done.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
Performing docking (random seed: 1203846424) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1      -0.4487          0          0
   2      -0.4439      1.716      2.291
   3      -0.3988      3.382      8.445
   4       -0.349      2.303      3.492
   5      -0.3249      4.164      7.094
   6      -0.1106       3.33      8.012
   7     -0.01736      2.119      3.948
   8            0      4.818      9.819
   9     0.004521      5.385      10.16

An internal error occurred in ../../../src/lib/model.cpp(682). 

Please report bugs through the Issue Tracker on GitHub 
(https://github.com/ccsb-scripps/AutoDock-Vina/issues)., so

Computer system: Mac Pro (Mid 2010), 3.46 GHz 6-Core Intel Xeon, 32 GB 1333 MHz DDR3
OS: 10.13.6

command-line: vina --size_x 10.283 --size_y 5.075 --size_z 24.783  --center_x -296.579 --center_y -1485.049 --center_z 1274.203  --ligand FAD_ideal.pdbqt --receptor 3qvp_A.pdbqt

No confguration file.

random seed: 1203846424

PDBQT files attached as .txt files (note output file is zero bytes...)

[3qvp_A.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/10042461/3qvp_A.pdbqt.txt)
[FAD_ideal.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/10042466/FAD_ideal.pdbqt.txt)
[FAD_ideal_out.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/10042470/FAD_ideal_out.pdbqt.txt)

**Comment by rwxayheee** [comment]
Hi,

I noticed that the atoms in the receptor pdbqt all have partial charge = 0. Can you please track how the receptor pdbqt was generated?
Also, since PDB files are parsed by columns (characters in line) and the coordinate filed has a limited number of digits and characters (8 including 3 decimal places), if you have atomic coordinates like -1485.049 in your input PDB file, there might be a problem reading it. In your pdbqt file, there are no atoms with coordinates in that range. You might want to try changing the center of box, or translating the initial coordinates in the input PDB.

Bests,
Amy

From: hrp1000 ***@***.***>
Date: Friday, November 18, 2022 at 10:18 AM
To: ccsb-scripps/AutoDock-Vina ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ccsb-scripps/AutoDock-Vina] internal error occurred in ../../../src/lib/model.cpp(682) (Issue #156)
error message - AutoDock Vina v1. 2. 3 ################################################################# If you used AutoDock Vina in your work, please cite: J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli AutoDock Vina 1. 2. 0: New


error message -

AutoDock Vina v1.2.3
#################################################################

If you used AutoDock Vina in your work, please cite:
J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli
AutoDock Vina 1.2.0: New Docking Methods, Expanded Force
Field, and Python Bindings, J. Chem. Inf. Model. (2021)
DOI 10.1021/acs.jcim.1c00203
O. Trott, A. J. Olson,
AutoDock Vina: improving the speed and accuracy of docking
with a new scoring function, efficient optimization and
multithreading, J. Comp. Chem. (2010)
DOI 10.1002/jcc.21334
Please see https://github.com/ccsb-scripps/AutoDock-Vina<https://urldefense.com/v3/__https:/github.com/ccsb-scripps/AutoDock-Vina__;!!KGKeukY!0lx8kowJwJJjvQu-TTZCDMJ2UtH8o4dsHmmxCC6jH99AJYLtzTBMkDUIDF_KGylf4rncyvv9LRpvB_xMHyRcNTiPxbs$> for
more information.

#################################################################

Output will be FAD_ideal_out.pdbqt
Scoring function : vina
Rigid receptor: 3qvp_A.pdbqt
Ligand: FAD_ideal.pdbqt
Grid center: X -296.579 Y -1485.05 Z 1274.2
Grid size : X 10.283 Y 5.075 Z 24.783
Grid space : 0.375
Exhaustiveness: 8
CPU: 0
Verbosity: 1

Computing Vina grid ... done.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
Performing docking (random seed: 1203846424) ...
0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

________________________________

mode | affinity | dist from best mode
| (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1 -0.4487 0 0
2 -0.4439 1.716 2.291
3 -0.3988 3.382 8.445
4 -0.349 2.303 3.492
5 -0.3249 4.164 7.094
6 -0.1106 3.33 8.012
7 -0.01736 2.119 3.948
8 0 4.818 9.819
9 0.004521 5.385 10.16

An internal error occurred in ../../../src/lib/model.cpp(682).

Please report bugs through the Issue Tracker on GitHub
(https://github.com/ccsb-scripps/AutoDock-Vina/issues<https://urldefense.com/v3/__https:/github.com/ccsb-scripps/AutoDock-Vina/issues__;!!KGKeukY!0lx8kowJwJJjvQu-TTZCDMJ2UtH8o4dsHmmxCC6jH99AJYLtzTBMkDUIDF_KGylf4rncyvv9LRpvB_xMHyRcla-lg_o$>)., so

Computer system: Mac Pro (Mid 2010), 3.46 GHz 6-Core Intel Xeon, 32 GB 1333 MHz DDR3
OS: 10.13.6

command-line: vina --size_x 10.283 --size_y 5.075 --size_z 24.783 --center_x -296.579 --center_y -1485.049 --center_z 1274.203 --ligand FAD_ideal.pdbqt --receptor 3qvp_A.pdbqt

No confguration file.

random seed: 1203846424

PDBQT files attached as .txt files (note output file is zero bytes...)

3qvp_A.pdbqt.txt<https://urldefense.com/v3/__https:/github.com/ccsb-scripps/AutoDock-Vina/files/10042461/3qvp_A.pdbqt.txt__;!!KGKeukY!0lx8kowJwJJjvQu-TTZCDMJ2UtH8o4dsHmmxCC6jH99AJYLtzTBMkDUIDF_KGylf4rncyvv9LRpvB_xMHyRc2Bf23d0$>
FAD_ideal.pdbqt.txt<https://urldefense.com/v3/__https:/github.com/ccsb-scripps/AutoDock-Vina/files/10042466/FAD_ideal.pdbqt.txt__;!!KGKeukY!0lx8kowJwJJjvQu-TTZCDMJ2UtH8o4dsHmmxCC6jH99AJYLtzTBMkDUIDF_KGylf4rncyvv9LRpvB_xMHyRc9Ua_BE4$>
FAD_ideal_out.pdbqt.txt<https://urldefense.com/v3/__https:/github.com/ccsb-scripps/AutoDock-Vina/files/10042470/FAD_ideal_out.pdbqt.txt__;!!KGKeukY!0lx8kowJwJJjvQu-TTZCDMJ2UtH8o4dsHmmxCC6jH99AJYLtzTBMkDUIDF_KGylf4rncyvv9LRpvB_xMHyRc6YL5F0Y$>

**Comment by hrp1000** [comment]
First off, many thanks for your rapid reply.

The PDBQT file for the receptor was produced from the PDB entry for 3qvp with obabel after I grep'd out all the non-ATOM entries:

obabel -xr -i pdb 3qvp_A.pdb -o pdbqt -O 3qvp_A.pdbqt

Problem solved - coordinates for center are completely wrong (by a scale factor of ~53...).

I used fpocket to find the binding pockets, and I inadvertently did an incorrect divide by 3 (number of coordinates for each entry...) when calculating the centre of the binding pocket rather than the number of contributing sets of coordinates (159 in this case). D'oh...

**Comment by rwxayheee** [comment]
Hi, I tried the same command with obabel 2.4.1 and it can generate Gasteiger charges for receptor pdbqt file, although the charges will be neglected by Vina so it seems ok if we have all 0 there. Initially I thought obabel did not parse the coordinates properly because of the digit limits. Glad it worked after changing the center of box :)
