### ISSUE TITLE
About the vina tutorial

### ISSUE THREAD

**Issue by manuflores** [ccsb-scripps/AutoDock-Vina#24]
I'm following the great tutorial you guys made for vina recently. I have two questions hope that you can point me in the right direction, or make the contact with someone that could help me out: 

1. On [step 3 ](https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#optional-generating-affinity-maps-for-autodock-ff)of the tutorial, needs a script called `prepare_gpf.py` in the `<autodock-vina_directory>/example/autodock_scripts` directory. Could you point me to how to download that directory? As a note, I downloaded vina from the github. I also checked on the supplementary data of the Nature protocols paper, but it seems that is not the right place to look for.

2. More generally: do you recommend reference to learn how to get a grid box for docking? And, if I understand correctly, using autodock4 forcefield to compute the affinity map helps bypass the need to specify the grid box, correct? Would you recommend using ad4 instead of specifying the box?

Thank you and kudos to your work !

**Comment by diogomart** [comment]
Hello,

1. the scripts are here: https://github.com/ccsb-scripps/AutoDock-Vina/tree/develop/example/autodock_scripts

2. search dimensions and precalculated grid maps (i.e. the box) are always required. The best is to use a molecular visualizer (pymol, vmd, autodocktools/pmv, chimera, AGFR-gui) to see how the box fits the receptor. Ligands will dock inside that box because there is an energy penalty for ligand atoms that go outside during the search. Deciding the box location and dimensions is subjective and depends on where you want ligands to dock.
