### ISSUE TITLE
Charged ligands and receptors

### ISSUE THREAD

**Issue by vsheg** [ccsb-scripps/AutoDock-Vina#317]
Hi!

Given that Vina uses a "knowledge-based" scoring function, which ignores partial charges, can Vina be used to reliably estimate binding affinities between charged molecules?

For example, I have a receptor with a charged Lys (NH3+) and a deprotonated ligand (O-).

1. Will Vina's score correctly estimate the interaction, or are "O" and "O-" atoms indistinguishable?
2. Were charged molecules used to train and validate Vina's score parameters?
3. Could I use Vina to screen libraries containing charged molecules and especially **protomers**?
4. Could more complex cases be accounted for, e.g., ligands with a phosphonium (Ph3P+) group?

I have not found peer-reviewed papers that explicitly claim this is possible, but I found a [preprint](https://www.biorxiv.org/content/10.1101/212514v1.article-metrics) stating that Vina works better with charged ligands than even AutoDock, which has a Coulombic interaction term:

> Interestingly, AutoDock Vina performs better for charged and uncharged ligands compared to AutoDock.

I don't understand how this might be possible. I would really appreciate it if you could help me figure this out.

**Comment by diogomart** [comment]
Hi,

Excellent questions.

Docking scores are generally not to be trusted, at least not too much.

1. Yes "O" and "O-" are often the same in Vina.
2. Yes
3. The H-bond term discriminates donors from acceptors, so yes, there is some level of resolution, although the position of the H atom is ignored. For example, hydroxyl O is both donor and acceptor, pyridine N is acceptor, pyrrole N is donor, and N-methyl pyrrole N is neither.
4. No, there is no H-bond donor P, so vina has no way to model the positive charge.

Charge-charge interactions between target and ligand don't necessarily result in higher affinity, because charged groups need to be desolvated for binding. It's almost like vina got lucky by ignoring most of the physics, as most of the physics cancels itself out.

**Comment by vsheg** [comment]
@diogomart Thank you for the clear response. I'll close the issue in a few days if I don't have any follow-up questions.
