### ISSUE TITLE
Questions about calculating intramolecular energy for a ligand

### ISSUE THREAD

**Issue by tmcgrath325** [ccsb-scripps/AutoDock-Vina#349]
Hi Autodock dev team and users,

Thanks for building and maintaining this fantastic tool, and thanks for taking the time to read this.

To make sure that I understand the Vina scoring function, I'm putting together a quick and dirty reimplementation of it based on the [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3041641/) to see if I can recalculate scores for particular poses. It seems like I'm able to match the *inter*molecular component of the score, but I'm getting a little tripped up by the *intra*molecular part.

Assuming that I'm correctly assigning atom types and calculating potentials appropriately for atom pairs, my guess is that my issues might be coming from choosing incorrect sets of atom pairs to be evaluated for the intramolecular score. Based on the paper and reading through some of the source code, my understanding of the choice of atom pairs is as follows:
- exclude hydrogens
- exclude all pairs that are connected within 1, 2, or 3 covalent bonds
- exclude all pairs with coordinates that are further apart than the cutoff (8 angstroms)
- keep all other pairs (without double dipping)

For these atom pairs, potentials are calculated in the same was as ligand-protein ones.

Is that approach correct? When using atom pairs chosen in this way, I'm consistently getting getting higher scores for individual components of the scoring function, which might indicate that I'm keeping some pairs that should be excluded.

Here's a particular ligand I'm using for testing...
```
REMARK SMILES Cc1cc(C)cc(NC(=O)Cc2ccc(OC(C)(C)C(=O)O)cc2)c1
REMARK SMILES IDX 15 1 14 2 13 3 12 4 23 5 24 6 16 7 17 8 18 9 19 10 20 11
REMARK SMILES IDX 21 12 22 13 11 15 9 16 10 17 8 18 7 20 25 21 6 22 2 23 4 24
REMARK SMILES IDX 3 25 1 26 5 27
REMARK H PARENT 22 14 8 19
REMARK Flexibility Score: inf
ROOT
ATOM      1  C   UNL     1      19.351  16.715  41.509  1.00  0.00     0.121 A 
ATOM      2  C   UNL     1      19.317  17.904  40.827  1.00  0.00     0.047 A 
ATOM      3  C   UNL     1      18.398  18.886  41.203  1.00  0.00     0.008 A 
ATOM      4  C   UNL     1      17.506  18.721  42.240  1.00  0.00    -0.038 A 
ATOM      5  C   UNL     1      18.447  16.520  42.574  1.00  0.00     0.047 A 
ATOM      6  C   UNL     1      17.562  17.513  42.908  1.00  0.00     0.008 A 
ENDROOT
BRANCH   1   7
ATOM      7  O   UNL     1      20.240  15.735  41.171  1.00  0.00    -0.476 OA
BRANCH   7   8
ATOM      8  C   UNL     1      19.996  14.661  40.348  1.00  0.00     0.199 C 
ATOM      9  C   UNL     1      18.621  14.881  39.689  1.00  0.00     0.069 C 
ATOM     10  C   UNL     1      21.020  14.657  39.201  1.00  0.00     0.069 C 
BRANCH   8  11
ATOM     11  C   UNL     1      20.049  13.330  40.949  1.00  0.00     0.347 C 
ATOM     12  O   UNL     1      19.365  13.003  41.923  1.00  0.00    -0.248 OA
BRANCH  11  13
ATOM     13  O   UNL     1      20.914  12.341  40.419  1.00  0.00    -0.478 OA
ATOM     14  H   UNL     1      21.360  11.750  41.094  1.00  0.00     0.296 HD
ENDBRANCH  11  13
ENDBRANCH   8  11
ENDBRANCH   7   8
ENDBRANCH   1   7
BRANCH   4  15
ATOM     15  C   UNL     1      16.547  19.775  42.615  1.00  0.00     0.135 C 
BRANCH  15  16
ATOM     16  C   UNL     1      17.288  20.981  43.137  1.00  0.00     0.228 C 
ATOM     17  O   UNL     1      17.890  20.865  44.201  1.00  0.00    -0.274 OA
ATOM     18  N   UNL     1      17.260  22.164  42.400  1.00  0.00    -0.326 N 
ATOM     19  H   UNL     1      16.709  22.174  41.481  1.00  0.00     0.169 HD
BRANCH  18  20
ATOM     20  C   UNL     1      17.915  23.362  42.781  1.00  0.00     0.041 A 
ATOM     21  C   UNL     1      18.874  24.019  42.066  1.00  0.00     0.029 A 
ATOM     22  C   UNL     1      17.575  23.963  44.003  1.00  0.00     0.029 A 
ATOM     23  C   UNL     1      19.487  25.197  42.488  1.00  0.00    -0.049 A 
ATOM     24  C   UNL     1      18.134  25.113  44.477  1.00  0.00    -0.049 A 
ATOM     25  C   UNL     1      19.103  25.730  43.698  1.00  0.00     0.007 A 
ATOM     26  C   UNL     1      20.525  25.863  41.660  1.00  0.00     0.044 C 
ATOM     27  C   UNL     1      17.740  25.719  45.787  1.00  0.00     0.044 C 
ENDBRANCH  18  20
ENDBRANCH  15  16
ENDBRANCH   4  15
TORSDOF 7
```

... for which I generated the following table of atom pairs, where each row represents all of the other atoms that interact with a particular atom:
```
 # Atoms interacting with...                                Atom Number
 [12, 13, 15, 16, 17, 18, 20, 21, 22]                       # 1
 [9, 10, 11, 12, 13, 16, 17, 18, 20, 21, 22, 23]            # 2
 [8, 9, 10, 11, 12, 13, 17, 18, 20, 21, 22, 23, 24, 25, 26] # 3
 [7, 8, 9, 10, 11, 12, 13, 20, 21, 22, 23, 24, 25, 26, 27]  # 4
 [9, 10, 11, 12, 13, 16, 17, 18, 20, 21, 22]                # 5
 [8, 9, 10, 11, 12, 13, 17, 18, 20, 21, 22, 23, 24]         # 6
 [15, 16, 17, 18]                                           # 7
 [15, 16, 17]                                               # 8
 [15, 16, 17, 18]                                           # 9
 [15]                                                       # 10
 [15]                                                       # 11
 [15]                                                       # 12
 []                                                         # 13
 [21, 22, 23, 24, 25, 26, 27]                               # 15
 [23, 24, 25, 26, 27]                                       # 16
 [21, 22, 23, 24, 25, 26, 27]                               # 17
 [25, 26, 27]                                               # 18
 []                                                         # 20
 [27]                                                       # 21
 [26]                                                       # 22
 []                                                         # 23
 []                                                         # 24
 []                                                         # 25
 [27]                                                       # 26
 []                                                         # 27
```

Here's a plot of the ligand with bonds, for reference: 
![testligand](https://github.com/user-attachments/assets/2370422d-0996-43a1-a6cc-27e6260e468f)

Do I have the right idea?

While it's not central to my question about atom pairs, I've included below what I've been using to check my understanding of the scoring against Vina itself:

### Code snippet used to generate c_intra for each part of the scoring function
```python
scorer = Vina(sf_name="vina")
scorer.set_receptor(protein_path)

results = []
for i in range(5):
    weights = tuple([j == i for j in range(7)])
    scorer.set_weights(weights)

    scorer.compute_vina_maps(
        center=[16.966, 16.623, 41.744], 
        box_size=[25, 25, 25]
    )

    scorer.set_ligand_from_file(mol_path)
    results.append(scorer.score())

with open(astex_dir + 'result_components.txt', 'w') as f:
    for res in results:
        f.write(str(res[5]) + '\n')
```

Output of the above, where each line is an unweighted component of the ligand's intra score (in the standard order):
```
10.586
67.753
0.703
7.491
0.0
```

### Python script for recalculating components of c_intra
```python
import math

# constants

VDW_RADII = {
    'CH':  1.9,
    'CP':  1.9,
    'O':   1.7,
    'OD':  1.7,
    'OA':  1.7,
    'ODA': 1.7,
    'N':   1.8,
    'ND':  1.8,
    'NA':  1.8,
    'NDA': 1.8,
}

# functions

def clamp(n, lo, hi):
    return min(hi,max(n,lo))

def dist(coords1, coords2):
    return math.sqrt(sum([(x - y)**2 for x, y in zip(coords1, coords2)]))
    
def optimaldist(atomtype1, atomtype2):
    return VDW_RADII.get(atomtype1) + VDW_RADII.get(atomtype2)

def ishydrophobe(atomtype):
    return atomtype == "CH" # ignoring other atomtypes that aren't present in the test ligand

def isacceptor(atomtype):
    return atomtype == "OA" or atomtype == "ODA" or atomtype == "NA" or atomtype == "NDA"

def isdonor(atomtype):
    return atomtype == "OD" or atomtype == "ODA" or atomtype == "ND" or atomtype == "NDA"

def gauss(coords1, type1, coords2, type2, offset, width):
    return math.exp(-(((dist(coords1, coords2) - optimaldist(type1, type2) - offset)/width))**2)

def gauss1(coords1, type1, coords2, type2):
    return gauss(coords1, type1, coords2, type2, 0, 0.5)

def gauss2(coords1, type1, coords2, type2):
    return gauss(coords1, type1, coords2, type2, 3, 2)

def repulsion(coords1, type1, coords2, type2):
    return min(dist(coords1,coords2) - optimaldist(type1, type2), 0)**2

def ramp(val, bad, good):
    lo = min(bad,good)
    hi = max(bad,good)
    return (clamp(val,lo,hi) - bad) / (good - bad)

def hydrophobic(coords1, type1, coords2, type2):
    if ishydrophobe(type1) and ishydrophobe(type2):
        return ramp(dist(coords1,coords2) - optimaldist(type1,type2), 1.5, 0.5)
    else:
        return 0

def hbonding(coords1, type1, coords2, type2):
    if ((isacceptor(type1) and isdonor(type2)) or (isacceptor(type2) and isdonor(type1))):
        return ramp(dist(coords1,coords2) - optimaldist(type1,type2), 0, -0.7)
    else:
        return 0

# data from particular ligand

coordinates = [
    [19.351, 16.715, 41.509], # 1
    [19.317, 17.904, 40.827], # 2
    [18.398, 18.886, 41.203], # 3
    [17.506, 18.721, 42.24 ], # 4
    [18.447, 16.52,  42.574], # 5
    [17.562, 17.513, 42.908], # 6
    [20.24,  15.735, 41.171], # 7
    [19.996, 14.661, 40.348], # 8
    [18.621, 14.881, 39.689], # 9
    [21.02,  14.657, 39.201], # 10
    [20.049, 13.33,  40.949], # 11
    [19.365, 13.003, 41.923], # 12
    [20.914, 12.341, 40.419], # 13
    [16.547, 19.775, 42.615], # 15
    [17.288, 20.981, 43.137], # 16
    [17.89,  20.865, 44.201], # 17
    [17.26,  22.164, 42.4  ], # 18
    [17.915, 23.362, 42.781], # 20
    [18.874, 24.019, 42.066], # 21
    [17.575, 23.963, 44.003], # 22
    [19.487, 25.197, 42.488], # 23 
    [18.134, 25.113, 44.477], # 24
    [19.103, 25.73,  43.698], # 25
    [20.525, 25.863, 41.66 ], # 26
    [17.74,  25.719, 45.787], # 27
]

atomtypes = [
    "CP",  "CH",  "CH",  "CH",  "CH", # 1,  2,  3,  4,  5
    "CH",  "OA",  "CP",  "CH",  "CH", # 6,  7,  8,  9,  10
    "CP",  "OA",  "ODA", "CH",  "CP", # 11, 12, 13, 15, 16
    "OA",  "ND",  "CP",  "CH",  "CH", # 17, 18, 20, 21, 22
    "CH",  "CH",  "CH",  "CH",  "CH", # 23, 24, 25, 26, 27
]

# note that these are indices for the above lists, NOT the serials of the atoms
intra_pairs = [ # excluding atoms within 3 covalent bonds of one another or greater than 8 angstroms away
    [12, 13, 14, 15, 16, 17, 18, 19, 20],
    [9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21],
    [8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24],
    [7, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 22, 23, 24, 25],
    [9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20],
    [8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22],
    [14, 15, 16, 17],
    [14, 15, 16],
    [14, 15, 16, 17],
    [14],
    [14],
    [14],
    [],
    [19, 20, 21, 22, 23, 24, 25],
    [21, 22, 23, 24, 25],
    [19, 20, 21, 22, 23, 24, 25],
    [23, 24, 25],
    [],
    [25],
    [24],
    [],
    [],
    [],
    [25],
    [],
]

def evaluate_potential_function(coordinates, atomtypes, allpairs, func):
    potential = 0
    for coords, atype, pairs in zip(coordinates, atomtypes, allpairs):
        for pairidx in pairs:
            potential = potential + func(coords, atype, coordinates[pairidx-1], atomtypes[pairidx-1])
    return potential

with open('recalculations.txt', 'w') as f:
    for func in [gauss1, gauss2, repulsion, hydrophobic, hbonding]:
        f.write(str(evaluate_potential_function(coordinates, atomtypes, intra_pairs, func)) + '\n')
```

Output of the above script, where the entries are the recalculated scores:
```
12.516457453275775
71.02000105089027
0.7046835040141604
9.814623380276732
0.0
```

Aside from the hydrogen bonding score of zero, the only score that seems to be roughly correct is the repulsion component.

**Comment by diogomart** [comment]
There are further exclusions to the non-bonded list: vina excludes any pair of atoms for which the distance doesn't change. This includes any pair within a rigid group of atoms. for example, the following pairs in your example above would be excluded:
```
26-27
18-16
18-27
21-27
```
(these are just a few examples of pairs that vina excludes, there are more.

**Comment by tmcgrath325** [comment]
That did the trick, thanks @diogomart! 🎉
It makes a lot of sense that anything invariant to bond rotations is excluded from the score.

**Comment by diogomart** [comment]
You are welcome!

**Comment by bafr008** [comment]
Hi,

In the same manner as @tmcgrath325 , I am also trying to replicate the Vina scoring function fully in python in order to get a full understanding of all the individual terms of the function and software. I have also manage to exactly replicate the intermolecular energy values for each component of the scoring function, but I am having issues with the intramolecular part. So far, following the replies in this thread, I have:
- excluded hydrogens
- excluded all pairs that are connected within 1, 2, or 3 covalent bonds
- excluded all pairs with coordinates that are further apart than the cutoff (8 angstroms)
- excluded all pairs within the same rigid group

Even with all this, it seems like I am getting higher values for both Gaussian terms when compared to the vina results:
<pre>Vina results:
1.688
3.646
0.0
0.0
0.0 

My results:
1.9483500770421602
6.0327621521555255
0.0
0.0
0.0
</pre>
I know my energy function calculation must be correct, as the intermolecular gives the right result. Any advice or idea why could this be happening? Am i missing another pair exclusion condition or is one of my implementations incorrect? My code for filtering intra pairs can be seen bellow:

```python
from rdkit import Chem
from rdkit.Chem import rdmolops
from openbabel import openbabel as ob
from openbabel import pybel
import numpy as np
from rdkit.Chem import rdmolops

def is_rotatable_bond_gnina(bond: ob.OBBond, desired_root: int) -> bool:
    if bond.GetBondOrder() != 1 and bond.GetBondOrder() != 2:
        return False
    if bond.IsAmide():
        return False
    if bond.IsInRing():
        return False

    begin = bond.GetBeginAtom()
    end = bond.GetEndAtom()

    def count_heavy_neighbors(atom: ob.OBAtom) -> int:
        return sum(1 for nbr in ob.OBAtomAtomIter(atom) if nbr.GetAtomicNum() > 1)

    hvy1 = count_heavy_neighbors(begin)
    hvy2 = count_heavy_neighbors(end)

    if hvy1 == 1 or hvy2 == 1:
        # allow bond if connected to desired root
        # if begin.GetIdx() == desired_root or end.GetIdx() == desired_root:
        if begin.GetIdx() == desired_root + 1 or end.GetIdx() == desired_root + 1:
            return True
        return False

    return True

def get_rigid_groups(mol_pybabel: pybel.Molecule, desired_root=0):
    mol_pybabel.OBMol.ConnectTheDots()
    mol_pybabel.OBMol.PerceiveBondOrders()
    num_atoms = mol_pybabel.OBMol.NumAtoms()
    bond_graph = [set() for _ in range(num_atoms)]
    rotatable_bonds = set()

    for bond in ob.OBMolBondIter(mol_pybabel.OBMol):
        a1 = bond.GetBeginAtomIdx() - 1
        a2 = bond.GetEndAtomIdx() - 1
        bond_graph[a1].add(a2)
        bond_graph[a2].add(a1)

        if bond.IsRotor(): ## openbabel check
        # if is_rotatable_bond_gnina(bond, desired_root): ## gnina-likeish check
            rotatable_bonds.add((min(a1, a2), max(a1, a2)))

    visited = [False] * num_atoms
    atom_to_group = [-1] * num_atoms
    group_id = 0

    for i in range(num_atoms):
        if visited[i]:
            continue
        stack = [i]
        while stack:
            current = stack.pop()
            if visited[current]:
                continue
            visited[current] = True
            atom_to_group[current] = group_id
            for neighbor in bond_graph[current]:
                if (min(current, neighbor), max(current, neighbor)) not in rotatable_bonds:
                    stack.append(neighbor)
        group_id += 1

    return atom_to_group

def pybel_to_rdkit(pybel_mol):
    # Convert Pybel mol to MOL block string
    molblock = pybel_mol.write("mol")
    # Load with RDKit from MOL block
    rdkit_mol = Chem.MolFromMolBlock(molblock, sanitize=True, removeHs=False)
    return rdkit_mol

def rdkit_bond_distance(rdkit_mol, idx1, idx2, max_dist=10):
    # Get shortest path length between atoms
    path_length = rdmolops.GetShortestPath(rdkit_mol, idx1, idx2)
    if len(path_length) == 0:
        return max_dist + 1  # no path found
    return len(path_length) - 1 

def get_ligand_intramolecular_pairs(mol: pybel.Molecule):
    atoms = mol.atoms

    # Get bond info
    rigid_groups = get_rigid_groups(mol)

    # Heavy atoms only
    heavy_atoms = [i for i, atom in enumerate(atoms) if atom.atomicnum != 1]

    rdkit_mol = pybel_to_rdkit(mol)

    coords = np.array([atom.coords for atom in atoms])

    pairs = []
    for i, idx1 in enumerate(heavy_atoms):
        for idx2 in heavy_atoms[i+1:]:
            # Skip if same rigid group
            if rigid_groups[idx1] == rigid_groups[idx2]:
                continue
            # Skip if bond distance <=3
            if rdkit_bond_distance(rdkit_mol, idx1, idx2) <= 3:
                continue
            distance = np.linalg.norm(coords[idx1] - coords[idx2])
            if distance >= 8.0:
                # skip pairs beyond cutoff
                continue
            pairs.append((idx1, idx2))
    return np.array(pairs, dtype=np.int32)

if __name__ == "__main__":
    ligand_file = "./temp_mol/2j78/2j78_lig_prepared.pdbqt"

    ligand_mol = next(pybel.readfile("sdf", ligand_file))

    ligand_intra_pairs = get_ligand_intramolecular_pairs(ligand_mol)

    print(f"Selected pairs are:")
    for i, pair in enumerate(ligand_intra_pairs):
        idx1, idx2 = pair
        print(f"Pair {i}: ({idx1}, {idx2})")
```
I am using the crystal ligand 2j78 from https://github.com/gnina/models/blob/master/data/PDBBind2016/README.md, which i convert to pdbqt with:
<pre>obabel ./_subsetDat/2j78/2j78_pdb.sdf -xr -h -O ./temp_mol/2j78/2j78_lig_prepared.pdbqt</pre> (if I do not add the hydrogen flag, then the result changes to 2.9005560838446423 and 10.87853376694633 for the gaussians).

The original SDF contains the following:
<pre>
2j78_ligand

Created by X-TOOL on Fri Nov 18 14:18:49 2016
 25 25  0  0  0  0  0  0  0  0999 V2000
    0.1250   11.4600   10.3170  C 0  0  0  1  0  3
    0.5030   11.3590   11.5760  N 0  0  0  1  0  2
    1.1740   12.1210    9.4020  C 0  0  0  2  0  4
   -1.1350   10.9800    9.9070  N 0  0  0  2  0  3
   -0.3610   10.7420   12.4840  O 0  0  0  2  0  2
    1.6700   13.3100    9.9680  O 0  0  0  2  0  2
    0.5390   12.4040    8.0430  C 0  0  0  2  0  4
    1.6100   12.6700    7.1400  O 0  0  0  2  0  2
   -0.2660   11.1900    7.5690  C 0  0  0  2  0  4
   -0.6380   11.3320    6.2030  O 0  0  0  2  0  2
   -1.5140   11.1240    8.4950  C 0  0  0  2  0  4
   -2.4280    9.9260    8.1640  C 0  0  0  3  0  4
   -1.7790    8.6990    8.4330  O 0  0  0  2  0  2
    2.0135   11.4235    9.2653  H 0  0  0  1  0  1
   -1.7755   10.5383   10.5819  H 0  0  0  1  0  1
    0.0371   10.7394   13.3466  H 0  0  0  1  0  1
    0.9538   13.9205   10.0976  H 0  0  0  1  0  1
   -0.1249   13.2784    8.1105  H 0  0  0  1  0  1
    1.2572   12.8523    6.2770  H 0  0  0  1  0  1
    0.3324   10.2739    7.6817  H 0  0  0  1  0  1
   -1.1352   10.5697    5.9305  H 0  0  0  1  0  1
   -2.0832   12.0564    8.3664  H 0  0  0  1  0  1
   -2.6971    9.9635    7.0981  H 0  0  0  1  0  1
   -3.3403    9.9910    8.7751  H 0  0  0  1  0  1
   -0.9920    8.6358    7.9047  H 0  0  0  1  0  1
  1  2  2  0  0  2
  1  3  1  0  0  1
  1  4  1  0  0  1
  2  5  1  0  0  2
  3  6  1  0  0  2
  3  7  1  0  0  1
  4 11  1  0  0  1
  7  8  1  0  0  2
  7  9  1  0  0  1
  9 10  1  0  0  2
  9 11  1  0  0  1
 11 12  1  0  0  2
 12 13  1  0  0  2
  3 14  1  0  0  2
  4 15  1  0  0  2
  5 16  1  0  0  2
  6 17  1  0  0  2
  7 18  1  0  0  2
  8 19  1  0  0  2
  9 20  1  0  0  2
 10 21  1  0  0  2
 11 22  1  0  0  2
 12 23  1  0  0  2
 12 24  1  0  0  2
 13 25  1  0  0  2
M  END
> <MOLECULAR_FORMULA>
C6H12N2O5

> <MOLECULAR_WEIGHT>
192.1

> <NUM_HB_ATOMS>
7  

> <NUM_ROTOR>
1  

> <XLOGP2>
-1.90

$$$$

</pre>

The final pdbqt looks like the following:
<pre>
REMARK  Name = 2J78_GOX_A_1451
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ATOM      1  C   UNK A   0       0.125  11.460  10.317  0.00  0.00    +0.000 C 
ATOM      2  N   UNK A   0       0.503  11.359  11.576  0.00  0.00    +0.000 NA
ATOM      3  C   UNK A   1       1.174  12.121   9.402  0.00  0.00    +0.000 C 
ATOM      4  N   UNK A   1      -1.135  10.980   9.907  0.00  0.00    +0.000 N 
ATOM      5  O   UNK A   0      -0.361  10.742  12.484  0.00  0.00    +0.000 OA
ATOM      6  O   UNK A   1       1.670  13.310   9.968  0.00  0.00    +0.000 OA
ATOM      7  C   UNK A   1       0.539  12.404   8.043  0.00  0.00    +0.000 C 
ATOM      8  O   UNK A   1       1.610  12.670   7.140  0.00  0.00    +0.000 OA
ATOM      9  C   UNK A   1      -0.266  11.190   7.569  0.00  0.00    +0.000 C 
ATOM     10  O   UNK A   1      -0.638  11.332   6.203  0.00  0.00    +0.000 OA
ATOM     11  C   UNK A   1      -1.514  11.124   8.495  0.00  0.00    +0.000 C 
ATOM     12  C   UNK A   1      -2.428   9.926   8.164  0.00  0.00    +0.000 C 
ATOM     13  O   UNK A   1      -1.779   8.699   8.433  0.00  0.00    +0.000 OA
ATOM     14  H   UNK A   1      -1.747  10.558  10.552  0.00  0.00    +0.000 HD
ATOM     15  H   UNK A   0      -0.113  10.659  13.384  0.00  0.00    +0.000 HD
ATOM     16  H   UNK A   1       0.942  13.939  10.088  0.00  0.00    +0.000 HD
ATOM     17  H   UNK A   1       2.204  11.904   7.108  0.00  0.00    +0.000 HD
ATOM     18  H   UNK A   1      -1.162  12.141   6.093  0.00  0.00    +0.000 HD
ATOM     19  H   UNK A   1      -0.982   8.628   7.885  0.00  0.00    +0.000 HD
TER 
</pre>

I am quite new to this field, so any help would be really appreciated.
