### ISSUE TITLE
How to use '--local_only'

### ISSUE THREAD

**Issue by flpan** [ccsb-scripps/AutoDock-Vina#6]
How can I correctly use '--local_only' to get the score, as in '--score_only'?I have tested that '-- score_only 'does not score as '-- score_only'.

**Comment by jeeberhardt** [comment]
Hi flpan,

Congratulations for finding the first issue!
It was fixed, Vina shows now the correct behavior and output the detailed energy contributions of the minimized pose when using `--local-only` argument. Compared to the previous version (1.1.2) , grid parameters (center_x, center_y, center_z and size_x, size_y, size_z) needs to be defined now.

If you have a substantial number of ligands to minimized, I would suggest you to use the Vina python bindings (https://autodock-vina.readthedocs.io/en/latest/docking_python.html) instead of the binary since you can retrieve energies directly without having to parse the output (https://autodock-vina.readthedocs.io/en/latest/vina.html#vina.vina.Vina.optimize).

Hope it helps,
Jerome.

**Comment by flpan** [comment]
Is this only fixed in the version of the source installation?Can't executables use --local_only yet?

**Comment by jeeberhardt** [comment]
Yes, the issue was fixed only in the source code, we didn't release yet the new binaries.

**Comment by flpan** [comment]
OK, thank you very much!Looking forward to the release of your binaries

**Comment by jeeberhardt** [comment]
Hi flpan,

We just published a new release: https://github.com/ccsb-scripps/AutoDock-Vina/releases/tag/v1.2.0

Let me know if it works for you now.

Jerome.
