### ISSUE TITLE
docking_zinc

### ISSUE THREAD

**Issue by lonelu** [ccsb-scripps/AutoDock-Vina#72]
Dear developers,

I am following the tutorial here: https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html. There are a few issues at my end if you could point out what I didn't do correctly. 

>mk_prepare_ligand.py -i 1s63_ligand.sdf -o 1s63_ligand.pdbqt
#-----------------------------------------
Traceback (most recent call last):
  File "~/Meeko/scripts/mk_prepare_ligand.py", line 145, in <module>
    ligand_prepared = preparator.write_pdbqt_string()
  File "/home/lonelu/miniconda3/envs/env_combs/lib/python3.8/site-packages/meeko/preparation.py", line 213, in write_pdbqt_string
    raise RuntimeError("Molecule not OK, refusing to write PDBQT\n\nLOG:\n%s" % self.log)
RuntimeError: Molecule not OK, refusing to write PDBQT
LOG:
atom number 24 has None type, mol name: 778
#------------------------------------------

> autogrid4 -p protein_tz.gpf -o protein_tz.glg
It seems like autogrid4 doesn't have -o option.  "autogrid4: unknown switch -o"

> vina --ligand 1s63_ligand.pdbqt --maps protein_tz --scoring ad4 --exhaustiveness 32 --out 1s63_ligand_ad4_out.pdbqt
The options don't work for vina. 

Best,
Lei

**Comment by diogomart** [comment]
Hi,

Thanks for reporting.

The example molecule has uppercase "CL" instead of "Cl" for chlorine and openbabel does not recognize it. Since openbabel  produces a molecule object without throwing errors, meeko tries to process the molecule but raises an error because one of the atoms has no type. Fixed in d9138769e6737d06714c4214318361f3ca1bbf45

The command line flag for autogrid4 output is `-l` not `-o`. FIxed in d9138769e6737d06714c4214318361f3ca1bbf45

The options should work for vina unless you have vina v1.1.2.

Best regards
