### ISSUE TITLE
Conformations and Docking

### ISSUE THREAD

**Issue by DarthSaddest** [ccsb-scripps/AutoDock-Vina#95]
A few questions:

1. Is there any significant downside to inputting a ligand as a 2D .pdbqt file rather than its 3d equivalent?
2. Assuming the answer to (1) is a **yes**, maybe Autodock Vina can integrate some RDKit functionality? As of now, their ETKDG provides the [best](https://pubs.acs.org/doi/abs/10.1021/ci2004658) 3D-structure generation of all non-commercial tools.
    - I can share a standalone script that can convert 2d .sdf to 3d equivalent.
3. That being said, does Vina alter the conformation of the ligand across poses? To what extent, even if I set very high values of `exhaustiveness`?
    - I used RDKit to generate about a hundred conformers (exhaustive) for a single ligand and ran Autodock (all specs being the same, alongside seed value) for each of them but the best scores varied widely.
5. If I [do a local energy minimization](https://autodock-vina.readthedocs.io/en/latest/docking_python.html) prior to docking, shall I expect the previous disparity to minimize?
    - I am not inclined to think so; energy minimization is generally [a lot less valuable](https://squonk.it/docs/cells/RDKit%20Conformers#rdkit-conformer-generation) when using ETKDG.
    - That being said, using `v.optimize()` outputs `ERROR: The ligand is outside the grid box. Increase the size of the grid box or center it accordingly around the ligand` and stops docking.
6. If I am looking at only the _best_ pose, I expect to set `dock(n_poses=1)`? But, best values are different when using `dock(n_poses=20)`

**Comment by diogomart** [comment]
1. Yes. Very significant. Even if the molecule is planar, some 2D representations have a different scale (e.g. bond lengths are shorter)
2. Such ETKDG to Vina integration can be achieved at the Python level, using Meeko: https://github.com/forlilab/Meeko
3. Vina rotates bonds that are rotatable. Bond lengths, angles, and improper dihedrals (e.g. planarity of sp2 atoms) are unchanged.
4. If minimizing the conformers yields fewer conformers, because some of them minimize towards a common conformer, the disparity should decrease. `v.optimize()` does not change bond lengths, bond angles, and impropers. `v.dock()` calls `v.optimize()` internally, several times.
5. Are you sure it's reproducible? Docking results vary from run to run (it's stochastic).

**Comment by DarthSaddest** [comment]
1. Thanks. 
2. Interesting package - I regret to have had missed this!
    - I wrote my own python script to generate 3D PDBQT conformations from a 2D SDF via RDKit (ETKDG) and fed each to `make_ligand4.py` (ADFR Suite).
    - Unless I am intending to dock with explicit water molecules or sample macrocyclic conformations, how is your tool better?
3.  If I read you correctly, Vina can generate some conformations **but** not all.
4. Understood.
5. I had used the same seed?

**Comment by diogomart** [comment]
2. For non-macrocyclic molecules, your script probably gives the same results as meeko, where results means atom types, rotatable bonds, and partial charges. Some rotatable bonds may differ because meeko makes tertiary amides rotatable (the C-N bond) if the substituents on the nitrogen are non-equivalent.
3. Yep, that's correct.
5. I can see this too, even from command line with `--num_modes 1`. will look into it. Thanks for reporting!
