### ISSUE TITLE
Problem in adding hydrogen and water in ligand preparation for hydrated docking

### ISSUE THREAD

**Issue by kajunes** [ccsb-scripps/AutoDock-Vina#97]
When i prepare ligand with mk_prepare_ligand.py script, both hydrogens are not added automatically and water molecules are badly added to the file and even bind to the ligand. How can i fix this?
[ligand.tar.gz](https://github.com/ccsb-scripps/AutoDock-Vina/files/8418532/ligand.tar.gz)
![hydrated](https://user-images.githubusercontent.com/103048137/161765586-045396b5-4c4e-4bc6-9371-8bff75cb633a.png)

**Comment by diogomart** [comment]
Hi, meeko does not add hydrogens since v0.3.0. The input molecule for meeko needs to be protonated.

The water positions are likely incorrect without hydrogens. But, Pymol often displays bonds between waters (even if the waters are in their expected positions) whenever two waters are close to each other.

**Comment by kajunes** [comment]
Thank you for the quick reply.

**Comment by diogomart** [comment]
You are welcome
